version: '3.3'

services:
  web:
    build: ./
    image: abdulzamad/cookbook
    command: flask run --host 0.0.0.0 --port 5000
    ports:
      - 5000:5000
    expose:
      # Opens port 3306 on the container
      - '5000'
    env_file:
      - ./.env